services:
  angular-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: demo-angular-app
    container_name: demo-app
    ports:
      - "8080:8080"

  aspnet-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: demo-dotnet-api
    environment:
      - ASPNETCORE_URLS=http://+:5000
    restart: always
    ports:
      - "5000:5000"
    container_name: demo-server

  nginx:
    image: nginx:alpine
    container_name: demo-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - angular-client
      - aspnet-server