services:
  angular-client:
    build:
      context: ./dist
      dockerfile: Dockerfile
    image: demo-angular-app
    container_name: demo-app
    networks:
      - demo

  aspnet-server:
    build:
      context: ./publish
      dockerfile: Dockerfile
    image: demo-dotnet-api
    environment:
      - ASPNETCORE_URLS=http://+:5000
    restart: always
    container_name: demo-server
    networks:
      - demo

networks:
  demo:
    driver: bridge
