apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-angular-app
  labels:
    app: my-angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-angular-app
  template:
    metadata:
      labels:
        app: my-angular-app
    spec:
      containers:
      - name: my-angular-app
        image: demo-angular-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-angular-app-service
spec:
  selector:
    app: my-angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80