name: Deploy to Local Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Angular Docker Image
        run: docker build -t demo-app ./client

      - name: Build ASP.NET Core Docker Image
        run: docker build -t demo-api ./server/API_Identity

      - name: Save Docker Images as Tar Files
        run: |
          docker save -o angular-app.tar demo-app
          docker save -o dotnet-api.tar demo-api

      - name: Upload Docker Images as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: "*.tar"

  copy:
    name: Copy Files to Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker Image Artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker-images

      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "angular-app.tar,dotnet-api.tar,docker-compose.yml"
          target: "/home/${{ secrets.SSH_USERNAME }}/app"

  deploy:
    name: Deploy on Server
    runs-on: ubuntu-latest
    needs: copy
    steps:
      - name: SSH into Server & Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/app
            docker load -i angular-app.tar
            docker load -i dotnet-api.tar
            docker compose down
            docker compose up -d --force-recreate
